import manifest from './press-manifest.json';

/**
 * Press kit (/ja/press/, /en/press/).
 *
 * Files live in static/press/<id>/ and are served as-is (original resolution).
 * Thumbnails (*-thumb.jpg), the ZIP and press-manifest.json (which files exist,
 * with sizes) are generated by tools/press/build-assets.sh.
 * Titles and labels are in src/lib/i18n/translations/press.ts, keyed by `id`.
 */

export type PressRelease = {
	id: string;
	/** ISO date, shown as YYYY.MM.DD */
	date: string;
	pdf: string;
	images: string[];
	zip: string;
};

/** Newest first */
export const PRESS_RELEASES: PressRelease[] = [
	{
		id: '2026-10-06-ceatec-award',
		date: '2026-10-06',
		pdf: '2026-10-06_press-release.pdf',
		images: ['2026-10-06_trails-positioning-image.png', '2026-10-06_astra-usage-image.png'],
		zip: '2026-10-06_press-kit.zip'
	}
];

export const pressDir = (id: string) => `/press/${id}`;

/** Thumbnail generated next to the original: foo.png → foo-thumb.jpg */
export const thumbName = (file: string) => file.replace(/\.[a-z]+$/i, '-thumb.jpg');

/** Logos offered for download: transparent PNG, 3000×824 (static/press/logo/) */
export const PRESS_LOGOS = [
	{ key: 'black', src: '/press/logo/zeteoh-logo-black.png', download: 'zeteoh-logo-black.png' },
	{ key: 'white', src: '/press/logo/zeteoh-logo-white.png', download: 'zeteoh-logo-white.png' }
] as const;

export type PressFile = { url: string; size: number };

const files = manifest as Record<string, Record<string, number>>;

/** File URL and size if it has been placed (per the manifest), otherwise null */
export function pressFile(id: string, name: string): PressFile | null {
	const size = files[id]?.[name];
	return size === undefined ? null : { url: `${pressDir(id)}/${name}`, size };
}

/** Everything the page needs for one release */
export function releaseDownloads(release: PressRelease) {
	return {
		id: release.id,
		date: release.date,
		pdf: pressFile(release.id, release.pdf),
		zip: pressFile(release.id, release.zip),
		images: release.images.map((name) => ({
			name,
			file: pressFile(release.id, name),
			thumb: pressFile(release.id, thumbName(name))
		}))
	};
}
